image: node:latest

variables:
  GIT_STRATEGY: fetch

cache:
  paths:
    - node_modules/


before_script:
  - npm install

unit-tests:
  script:
   - npm run test:ci


publish:
  scripts:
  # -
  only:
  - master

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - execute-script-for-job1
  only:
    - master
  tags:
    - docker
