image: node:latest

variables:
  GIT_STRATEGY: fetch

cache:
  paths:
    - node_modules/

before_script:
  - npm install

unit-tests:
  script:
   - npm run test:ci

#lint code

#lint commits

commit-lint:
git describe --abbrev=0 --tags
  script:
    - export LAST_TAG=$(git describe --abbrev=0 --tags)
    -


#publish:
#  scripts:
#   -
#  only:
#  - master

stages:
  - build
  - test
  - deploy
